######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 01:47:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
