######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 10 06:45:38 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

QT += network multimedia
CONFIG -= app_bundle
CONFIG += console

# Input
HEADERS += udpaudio.h
SOURCES += udpaudio.cpp
