######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 13 09:02:37 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testobjects.h xmlmapper.h
SOURCES += main.cpp xmlmapper.cpp
