######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 18 02:18:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test.h
SOURCES += main.cpp
